# Generated by Django 4.2.30 on 2026-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: ChatGPT Enterprise', max_length=100, unique=True)),
                ('webhook_slug', models.SlugField(help_text='Creates a unique URL ending: /api/v1/ingest/<slug>/', unique=True)),
                ('email_json_path', models.CharField(help_text="Dictionary key holding the user's email. Ex: 'actor.email' or 'email'", max_length=100)),
                ('action_json_path', models.CharField(help_text="Dictionary key holding the log event. Ex: 'event_type'", max_length=100)),
                ('value_json_path', models.CharField(blank=True, help_text="Optional. Key holding point metrics. Ex: 'complexity'", max_length=100)),
                ('default_value', models.FloatField(default=1.0, help_text='Fallback points if value_json_path fails or is empty.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
