# Generated by Django 4.2.30 on 2026-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text="Must match the tool_name recorded on ActivityLog (e.g. 'github_copilot').", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Friendly name for dashboards. Ex: 'GitHub Copilot Enterprise'.", max_length=120)),
                ('monthly_cost_per_seat_usd', models.FloatField(default=0.0, help_text='Per-seat subscription cost.')),
                ('minutes_saved_per_action', models.FloatField(default=2.0, help_text='Estimated minutes of developer time each action saves.')),
                ('avg_hourly_rate_usd', models.FloatField(default=80.0, help_text='Blended hourly rate used to translate time saved into dollars.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
