# Generated by Django 4.2.30 on 2026-04-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('leaderboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('department1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_dept1', to='users.department')),
                ('department2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_dept2', to='users.department')),
            ],
        ),
    ]
