# Generated by Django 4.2.30 on 2026-04-22 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0003_clash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: 'Spring 2026' or 'Q2 Showdown'", max_length=100, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False, help_text='True once results are frozen into the Hall of Fame.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActionFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('badge', 'Badge'), ('quest', 'Quest'), ('streak', 'Streak'), ('milestone', 'Milestone'), ('clash', 'Clash'), ('season', 'Season'), ('rival', 'Rival')], db_index=True, max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='⚡', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('final_score', models.FloatField()),
                ('department_name', models.CharField(blank=True, help_text='Snapshot of dept name at archive time.', max_length=100)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='leaderboard.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['season', 'rank'],
                'unique_together': {('season', 'user')},
            },
        ),
    ]
