# Generated by Django 4.2.30 on 2026-04-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_points', models.FloatField()),
                ('multiplier_applied', models.FloatField()),
                ('final_points', models.FloatField()),
                ('reason', models.CharField(blank=True, help_text='Reason for specific point calculation, like anti-cheat limits.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='ingestion.activitylog')),
            ],
        ),
    ]
